{{- if not .Values.harbor.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-harbor-sync.fullname" . }}-harbor
  labels:
    {{- include "helm-harbor-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  HARBOR_USER: {{ .Values.harbor.user | quote }}
  HARBOR_PASS: {{ .Values.harbor.pass | quote }}
{{- end }}
