apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-harbor-sync.fullname" . }}-proxy
  labels:
    {{- include "helm-harbor-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  selector:
    {{- include "helm-harbor-sync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
